version: '3.8'
services:
  crawler:
    build: .
    ports:
      - "3000:3000"  # Your application port
      - "5900:5900"  # VNC port
      - "6080:6080"  # noVNC web interface
    volumes:
      - .:/app
    environment:
      - DISPLAY=:99